image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release
  - staging
  - production

variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  except:
    - tags

test1:
  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  services: []
  before_script: []
  stage: test
  script:
    - echo "test1"
  except:
    - tags

test2:
  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  services: []
  before_script: []
  stage: test
  script:
    - echo "test2"
  except:
    - tags

# Non-master branches and tags will be released with :<ref_name> as the tag
release-by-name:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  except:
    - master

# Master will be released with :latest as the tag
release-master:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

auto-deploy-master:
  image: google/cloud-sdk
  stage: staging
  environment: staging
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ~/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
    - gcloud config set project $PROJECT_NAME
    - gcloud --quiet config set container/cluster $CLUSTER_NAME
    - gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
    - gcloud --quiet container clusters get-credentials $CLUSTER_NAME
  script:
    - kubectl patch deployment $STAGING_SERVICE_NAME -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$STAGING_SERVICE_NAME"'","image":"'"$CI_REGISTRY_IMAGE:$CI_BUILD_REF"'"}]}}}}'
  only:
    - master

auto-deploy-tags:
  stage: production
  environment: production
  script:
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF registry.heroku.com/$HEROKU_PROD_APP/web
    - docker push registry.heroku.com/$HEROKU_PROD_APP/web
  only:
    - tags

deploy to staging:
  stage: staging
  environment: staging
  script:
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF registry.heroku.com/$HEROKU_STAGING_APP/web
    - docker push registry.heroku.com/$HEROKU_STAGING_APP/web
  when: manual
  except:
    - master
    - tags

deploy to production:
  stage: production
  environment: production
  script:
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF registry.heroku.com/$HEROKU_PROD_APP/web
    - docker push registry.heroku.com/$HEROKU_PROD_APP/web
  when: manual
  only:
    - master
